# Generated by Django 4.0.2 on 2022-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_ads_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='poster',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
