# Generated by Django 4.0.2 on 2022-02-19 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_ads_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ads.user'),
            preserve_default=False,
        ),
    ]
