# Generated by Django 4.0.2 on 2022-02-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ads_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ads.user'),
        ),
    ]
