# Generated by Django 4.0.2 on 2022-02-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ads_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
