# Generated by Django 4.0.2 on 2022-02-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_ads_address_alter_ads_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.user'),
        ),
    ]
