# Generated by Django 4.0.2 on 2022-02-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_ads_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
